### ISSUE TITLE
Missing 64bit Linux SSL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [itsmeront/squeakssl#2]
```
I'd be great if you could ship 64bit so.SqueakSSL, too. I have attached a Zip 
file which includes your binaries and a 64bit-linux binary, which works here on 
Squeak 4.2.
```

Original issue reported on code.google.com by `timfelge...@gmail.com` on 13 May 2011 at 11:14

Attachments:
- [SqueakSSL-bin-0.1.4.zip](https://storage.googleapis.com/google-code-attachments/squeakssl/issue-2/comment-0/SqueakSSL-bin-0.1.4.zip)

**Comment by krono** [comment]
The Release v0.2.0 provides 32bit and 64bit libraries for linux
